version: '3'
services:
  # MySQL service
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Laravel (PHP) service
  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-container
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: todo_app
      DB_USERNAME: user
      DB_PASSWORD: password

  # Vue.js (Frontend) service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue-container
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: npm run serve